### PR TITLE
Feature record list and merkle tree

### PR DESCRIPTION
**Pull request by JikkuJose**
This PR has a bunch of other updates too, will take care from next time to give cleaner PRs.

### CODE REVIEW

**Comment by JikkuJose** [comment]
@nikhilkrishna it would be great if you can fix typo in [the commit][commit] while rebasing.

[commit]: https://github.com/big-org/toychain-record/pull/3/commits/e1a7a9a699887488bc41efca29da992fe2323402

**Comment by nikhilkrishna** [comment]
@JikkuJose @niksmac @kp666 @rakeshbs - have fixed typo as requested by Jikku and force pushed to github. Please rebase your local clones of the code so there are no conflicts.

**Comment by nikhilkrishna** [comment]
I am confused by this magic number - PADDER. 
What does it do and why is it needed ?

**Comment by JikkuJose** [comment]
PADDER is to pad the `array` of _hashes_ to make it the nearest power of two so that we can build the Merkle Tree. I didn't know what to pad with, so I used `'0'`.

**Pull request merged**
